$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent $PSScriptRoot
$imagesDir = Join-Path $repoRoot 'assets\images'
$outJson = Join-Path $imagesDir 'manifest.json'
$outJs = Join-Path $repoRoot 'assets\js\images-manifest.js'

if (-not (Test-Path $imagesDir)) {
  throw "Images folder not found: $imagesDir"
}

$extensions = @('.jpg','.jpeg','.png','.webp','.gif')
$files = Get-ChildItem -Path $imagesDir -File |
  Where-Object { $extensions -contains $_.Extension.ToLowerInvariant() } |
  Sort-Object -Property Name

$names = $files | ForEach-Object { $_.Name }

# Write JSON (array of filenames)
$names | ConvertTo-Json | Set-Content -Path $outJson -Encoding UTF8

# Write JS (global array) for file:// compatibility
$js = @()
$js += "// Auto-generated by scripts/generate-image-manifest.ps1"
$js += "// Do not edit by hand."
$js += "window.SFJ_IMAGE_MANIFEST = " + ($names | ConvertTo-Json -Compress) + ";"
$js -join "`n" | Set-Content -Path $outJs -Encoding UTF8

Write-Host "Wrote: $outJson"
Write-Host "Wrote: $outJs"
Write-Host ("Images: {0}" -f $names.Count)
